### ISSUE TITLE
[WARNING]: - mejo-.mariadb was NOT installed successfully.

### ISSUE THREAD

**Issue by K0XI** [systemli/userli#192]
Hello other Private Email intrested People!
Everytime I am trying to install it there is the Failure:
    - downloading role 'mariadb', owned by mejo-
    - downloading role from https://github.com/mejo-/ansible-role-mariadb/archive/master.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found

[WARNING]: - mejo-.mariadb was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

I Know that this is Because the file isn't there anymore, but I do not Know how to fix it.
Yours Sincely
Koxi

**Comment by t2d** [comment]
Hey Koxi, thank you for your bug report and your interest in Userli.
I think your problem was with `ansible-role-systemli` and I fixed the problem there.
https://github.com/systemli/ansible-role-userli/commit/371b34aea1a78412e33be03047486cc23108381c
Please let me know if you run into further problems.

**Comment by K0XI** [comment]
Hi t2d,
I got a new failure in the last step of the installation.
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
    fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'php7.3-apcu' is available"}
This was my failure. I tryed to install php7.3-apcu but it wasn't in the apt reposetory. Because I am using Linux Debian on my server I can't using brew to install it.
