### ISSUE TITLE
Postfix/Dovecote Requirements

### ISSUE THREAD

**Issue by mark4409** [systemli/userli#409]
I suspect I already know the answer to this but just wanted to check...

Will this application work if installed on a system with an already established mail server that uses mysql for virtual users and posfixadmin to administrate? Or does it ideally need to be set up on a fresh mail server installation with no database backend for users? I would also be using the server in conjunction with rspamd... is your application compatible with this setup?

**Comment by doobry-systemli** [comment]
Hey @mark4409. Userli is pretty opinionated about its database schema. I'd strongly recommend to setup a fresh userli installation and try to migrate your existing user data into it instead of trying to install userli over your existing mailserver.

We didn't integrate userli with rspamd yet, but I don't see a reason why this shouldn't work. Would be curious about your experience if you take that path.
